server:
  port: 8080
  servlet:
    session:
      persistent: true
      cookie:
        name: "RETURNBOXA_JSESSIONID"
  tomcat:
    max-http-header-size: 30000
    uri-encoding: "utf-8"

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/toDoList?zeroDateTimeBehavior=convertToNull&useSSL=true&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf8"
    username: "root"
    password: "star91ze"
  excel:
    path: "./excelFile/"
  image:
    path: "./itemImg/"
  json:
    path: "./json/"

    username: "kjy991@gmail.com"
